version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11.7
    working_directory: ~/oc_p13
    environment:
      DJANGO_SETTINGS_MODULE: oc_lettings_site.settings
      PYTHONPATH: /home/circleci/oc_p13
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run:
          name: Initialize Django for Pylint
          command: python -c "import os; os.environ['DJANGO_SETTINGS_MODULE'] = 'oc_lettings_site.settings'; import django; django.setup()"
      - run: pylint --load-plugins pylint_django .
      - run:
          name: Run Tests
          command: coverage run --source='.' manage.py test
      - run:
          name: Check Test Coverage
          command: coverage report --fail-under=80
      # Ajoutez un nouveau job pour le déploiement conditionnel à la fin des tests
      - deploy:
          name: Deploy to Render
          command: |
            if [ "$?" -eq 0 ]; then
              wget -O- https://api.render.com/deploy/srv-cmjpp36n7f5s73cdqm1g?key=Ql4DtbgsdBs
            fi
          when: on_success
          requires:
            - build

workflows:
  build_and_test_workflow:
    jobs:
      - build
      