version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.11.7
    working_directory: ~/project
    environment:
      DJANGO_SETTINGS_MODULE: oc_lettings_site.settings
      PYTHONPATH: ~/project
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pylint --load-plugins pylint_django .
      - run:
          name: Run Tests
          command: coverage report
      - run:
          name: Check Test Coverage
          command: coverage report --fail-under=80
