version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11.7
    working_directory: ~/oc_p13
    environment:
      DJANGO_SETTINGS_MODULE: oc_lettings_site.settings
      PYTHONPATH: /home/circleci/oc_p13
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run:
          name: Initialize Django for Pylint
          command: python -c "import os; os.environ['DJANGO_SETTINGS_MODULE'] = 'oc_lettings_site.settings'; import django; django.setup()"
      - run: pylint --load-plugins pylint_django .
      - run:
          name: Run Tests
          command: coverage run --source='.' manage.py test
      - run:
          name: Check Test Coverage
          command: coverage report --fail-under=80

workflows:
  build_and_test_workflow:
    jobs:
      - build
